### ISSUE TITLE
Rename adjacentPairs -> pairs

### ISSUE THREAD

**Issue by jsbean** [dn-m/Collections#172]
It's kind obvious, and unreasonably verbose.

**Comment by mossheim** [comment]
i actually prefer the specificity of adjacentPairs.. in supercollider `pairs` by default means consecutive pairs. it could also mean 'all possible pairs', aka cartesian product

**Comment by jsbean** [comment]
What's the diff between `adjacent pairs` and `consecutive pairs` ?
