### ISSUE TITLE
K-ary tree implementation

### ISSUE THREAD

**Issue by jsbean** [dn-m/Collections#20]
The desire here is to create an immutable, value-semantic tree structure. In the future, this will be used as the infrastructure for rhythm modeling, as well as an AST for an input language, among many other things.

Initial implementation:
```Swift
enum Tree <T> {
    indirect case branch([Tree])
    case leaf(T)
}
```

@brianlheim proposal:
```Swift
enum Tree <T> {
    indirect case node(T, [Tree])
}
```

Given the implementation with only a single `case`, it hints at just being a `struct`.

However, Swift won't let you do:

```Swift
struct Node <T> {
    let value: T
    let children: [Node] // no indirection in structs (yet?)
}
```

Also, we can't currently embed a nested generic type. For example: 

```Swift
struct Tree <T> {
    enum Node {
        case leaf(T)
        ...
    } 
}
```

**Comment by mossheim** [comment]
I don't know enough about `struct`, `enum`, and `indirect` in Swift to propose a solution, but this article looks relevant. Could we replace 
```swift
case Node(Tree<Element>,Element,Tree<Element>)
```
with 
```swift
case Node(Element,[Tree<Element>])
```
in
```swift
indirect enum Tree<Element: Comparable> {
    case Empty
    case Node(Tree<Element>,Element,Tree<Element>)
}
```
?

https://airspeedvelocity.net/2015/07/22/a-persistent-tree-using-indirect-enums-in-swift/

**Comment by jsbean** [comment]
I'm cool with that. Then again, what is the `empty` case for, exactly?

In that case, the following is a winner? :

```Swift
enum Tree <T> {
    indirect case node (T, [Tree])
}
```

> `indirect` here prevents the `enum` from blowing up recursively.

I don't think we necessarily need to carry over the `T: Comparable` constraint. It makes sense for the purposes of the article, where it's binary search tree.

Perhaps there are cases where that constraint is not needed (for example, an `AST`). 

In case it is needed, we can do something like:

```Swift
extension Tree where T: Comparable {
    func contains(element: T) -> Bool {
        ...
    }
}
```

**Comment by mossheim** [comment]
Agree that `T: Comparable` is an unnecessary constraint.

I think in this case, `Empty` is actually needed to signify an empty tree. A leaf then looks like
```swift
Node(Empty, Element, Empty)
```
(probably not correct syntax but you get the point).
